apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 534083940564.dkr.ecr.us-east-1.amazonaws.com/nginxapp:latest
        ports:
        - containerPort: 80
